### ISSUE TITLE
html5lib fails to build on Python 3.14 (uses removed ast.Str node)

### ISSUE THREAD

**Issue by sookach** [html5lib/html5lib-python#588]
setup.py uses ast.Str, which was removed in Python 3.14. As a result, attempting to build or install html5lib under Python 3.14 fails with an AttributeError, similar to below:
```zsh
       >   File "setup.py", line 93, in <module>
       >     isinstance(a.value, ast.Str)):
       >                         ^^^^^^^
       > AttributeError: module 'ast' has no attribute 'Str'
```
